version: '3.1'
services:
  db:
    image: mysql:8
    ports:
    - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: empuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: profiles
    volumes:
    - profiledata:/var/lib/mysql

  app:
    image: profiles:latest
    ports:
    - 8080:8080
    volumes:
    - profiledata:/data

volumes:
  profiledata: